modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"
issueTrackerURL="https://github.com/teamauroramods/Topsoil/issues"

[[mods]]
modId="topsoil"
version="${file.jarVersion}"
displayName="Topsoil"
displayURL="https://discord.gg/BgE4EpP"
logoFile="logo.png"
authors="Team Aurora"
description="Bogs and dirt caves"

[[dependencies.topsoil]]
modId="forge"
mandatory=true
versionRange="[35.1.10,)"
ordering="NONE"
side="BOTH"

[[dependencies.topsoil]]
modId="minecraft"
mandatory=true
versionRange="[1.16.4]"
ordering="NONE"
side="BOTH"

[[dependencies.topsoil]]
modId="abnormals_core"
mandatory=true
versionRange="[3.1.0,)"
ordering="AFTER"
side="BOTH"